spring:
  datasource:
    url: jdbc:mysql://wuyingdu.cn:3306/flowable?characterEncoding=utf8
    username: root
    password: Missxiao521..
    driver-class-name: com.mysql.cj.jdbc.Driver
flowable:
  async-executor-activate: false
  database-schema-update: true