spring:
  datasource:

    url: jdbc:mysql://localhost:3306/flowable?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
flowable:
#关闭定时任务JOB
  async-executor-activate: false
